version: "3.4"

services:
  main:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - DB_HOST=DB_HOST
      - DB_NAME=DB_NAME
      - DB_USERNAME=DB_USERNAME
      - DB_PASSWORD=DB_PASSWORD
      - SESSION_JWT=SESSION_JWT